### ISSUE TITLE
undefined method `map' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by robertybob** [andyw8/itunes_csv#1]
I've just tried getting this to work on Windows 10 for the first time, using iTunes 12.6.2.20 (the last version before they removed the Apps section). My Ruby installation is running from my F:\ (slave HD) while my iTunes library is on the C:\ in the 'Default' location.

I can't get it to work, all that is created is a zero byte "report.csv". The following error appears:

```
C:\Users\HTPC>itunes_csv -p "C:\Users\HTPC\Music\iTunes\iTunes Library.xml" > report.csv
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/andyw8-itunes-library-0.1.3/lib/itunes/library.rb:22:in `playlists': undefined method `map' for nil:NilClass (NoMethodError)
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/andyw8-itunes-library-0.1.3/lib/itunes/library.rb:26:in `find_playlist'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/andyw8-itunes-library-0.1.3/lib/itunes/library.rb:30:in `music'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/itunes_csv-0.0.3/lib/itunes_csv.rb:29:in `block in invoke'
        from F:/Ruby24-x64/lib/ruby/2.4.0/csv.rb:1183:in `generate'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/itunes_csv-0.0.3/lib/itunes_csv.rb:27:in `invoke'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/itunes_csv-0.0.3/bin/itunes_csv:7:in `<top (required)>'
        from F:/Ruby24-x64/bin/itunes_csv:23:in `load'
        from F:/Ruby24-x64/bin/itunes_csv:23:in `<main>'
```

**Comment by andyw8** [comment]
Hi Rob,

I just tried the gem with the latest iTunes on Mac (12.7.1.14) and it seems to still work, so I don't think the format has changed.

The error seems to indicate that it can't find the Music playlist in the file.

Is it possible you could share your XML file so that I can examine its structure? (You can email it if you prefer not to share publically).

**Comment by robertybob** [comment]
Turns out I'm an idiot, I think I was trying to run the program while ripping a CD. Works perfectly fine now that I've closed iTunes. Sorry for the panic (!) :)

**Comment by andyw8** [comment]
Oh, I'm surprised that having iTunes open would have affected this. But glad to hear you have a solution.
